services:
    db:
        image: postgres:16-alpine
        container_name: db
        env_file:
            - .env
        ports: [5432:5432]
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - store
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 3s
            retries: 5
    redis:
        image: redis:7.0.15-alpine
        container_name: redis
        ports: [6379:6379]
        volumes:
            - redis_data:/data
        networks:
            - store
    sidekiq:
        build: .
        container_name: sidekiq
        user: root
        command: bash -c "bundle exec sidekiq"
        working_dir: /app
        env_file:
            - .env
        tty: true
        stdin_open: true
        networks:
            - store
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
            - rubygems_store:/usr/local/bundle
    web:
        build: .
        container_name: web
        user: root
        command: bash -c "rm -rf tmp/pids/server.pid && bin/setup && bundle exec rails s -b 0.0.0.0 -p 3000"
        working_dir: /app
        ports: [3000:3000]
        volumes:
            - .:/app
            - rubygems_store:/usr/local/bundle
        env_file:
            - .env
        tty: true
        stdin_open: true
        networks:
            - store
        depends_on:
            - db
            - redis
volumes:
    postgres:
    redis_data:
    rubygems_store:

networks:
    store:
        name: store
